[supabase]
SUPABASE_URL = "https://YOUR_PROJECT.supabase.co"
SUPABASE_KEY = "YOUR_SERVICE_ROLE_KEY"  # only if needed, prefer anon if read-only
anon_key = "YOUR_PUBLIC_ANON_KEY"

[hubspot]
api_key = "YOUR_HUBSPOT_KEY"

[qbo]
client_id = "YOUR_CLIENT_ID"
client_secret = "YOUR_CLIENT_SECRET"
refresh_token = "YOUR_REFRESH_TOKEN"
realm_id = "YOUR_REALM_ID"

[app pw]
APP_PASSWORD = "your_secure_password"
